//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ErganhE7;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yeka.gr/E7")]
[System.Xml.Serialization.XmlRootAttribute("AnaggeliesE7", Namespace="http://www.yeka.gr/E7", IsNullable=false)]
public partial class AnaggeliesE7Type {
    
    private AnaggeliaE7Type[] anaggeliaE7Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AnaggeliaE7", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7Type[] AnaggeliaE7 {
        get {
            return this.anaggeliaE7Field;
        }
        set {
            this.anaggeliaE7Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yeka.gr/E7")]
public partial class AnaggeliaE7Type {
    
    private string f_aa_pararthmatosField;
    
    private string f_rel_protocolField;
    
    private string f_rel_dateField;
    
    private string f_ypiresia_sepeField;
    
    private string f_ypiresia_oaedField;
    
    private string f_ergodotikh_organwshField;
    
    private string f_kad_kyriaField;
    
    private string f_kad_deyt_1Field;
    
    private string f_kad_deyt_2Field;
    
    private string f_kad_deyt_3Field;
    
    private string f_kad_deyt_4Field;
    
    private string f_kad_pararthmatosField;
    
    private string f_kallikratis_pararthmatosField;
    
    private string f_eponymoField;
    
    private string f_onomaField;
    
    private string f_eponymo_patrosField;
    
    private string f_onoma_patrosField;
    
    private string f_eponymo_mitrosField;
    
    private string f_onoma_mitrosField;
    
    private string f_topos_gennhshsField;
    
    private string f_birthdateField;
    
    private AnaggeliaE7TypeF_sex f_sexField;
    
    private string f_yphkoothtaField;
    
    private string f_typos_taytothtasField;
    
    private string f_ar_taytothtasField;
    
    private string f_ekdousa_arxhField;
    
    private string f_date_ekdosisField;
    
    private string f_date_ekdosis_lixiField;
    
    private AnaggeliaE7TypeF_res_permit_inst f_res_permit_instField;
    
    private string f_res_permit_inst_typeField;
    
    private string f_res_permit_inst_arField;
    
    private string f_res_permit_inst_lixiField;
    
    private AnaggeliaE7TypeF_res_permit_ap f_res_permit_apField;
    
    private string f_res_permit_ap_typeField;
    
    private string f_res_permit_ap_arField;
    
    private string f_res_permit_ap_lixiField;
    
    private AnaggeliaE7TypeF_res_permit_visa f_res_permit_visaField;
    
    private string f_res_permit_visa_arField;
    
    private string f_res_permit_visa_fromField;
    
    private string f_res_permit_visa_toField;
    
    private AnaggeliaE7TypeF_marital_status f_marital_statusField;
    
    private string f_arithmos_teknonField;
    
    private string f_afmField;
    
    private string f_doyField;
    
    private string f_amikaField;
    
    private string f_amkaField;
    
    private string f_code_anergiasField;
    
    private string f_ar_vivliou_anilikouField;
    
    private string f_dieythinsiField;
    
    private string f_kallikratisField;
    
    private string f_tkField;
    
    private string f_tilField;
    
    private string f_faxField;
    
    private string f_emailField;
    
    private string f_epipedo_morfosisField;
    
    private AnaggeliaE7TypeF_professional_education f_professional_educationField;
    
    private string f_expertise_fieldField;
    
    private string f_subject_areaField;
    
    private string f_subject_groupField;
    
    private string f_education_agencyField;
    
    private string f_education_date_fromField;
    
    private string f_education_date_toField;
    
    private string f_durationField;
    
    private string f_education_yearField;
    
    private string f_fl1Field;
    
    private string f_fl2Field;
    
    private string f_fl3Field;
    
    private string f_fl4Field;
    
    private AnaggeliaE7TypeF_pc f_pcField;
    
    private string f_pc_otherField;
    
    private AnaggeliaE7TypeF_xaraktirismos f_xaraktirismosField;
    
    private AnaggeliaE7TypeF_sxeshapasxolisis f_sxeshapasxolisisField;
    
    private AnaggeliaE7TypeF_kathestosapasxolisis f_kathestosapasxolisisField;
    
    private AnaggeliaE7TypeF_oros f_orosField;
    
    private string f_eidikothtaField;
    
    private string f_apodoxesField;
    
    private string f_proslipsidateField;
    
    private string f_lixisymbashdateField;
    
    private string f_apolysisdateField;
    
    private string f_commentsField;

    private string f_lastdaydateField;

    private AnaggeliaE7TypeF_logosperatosis f_logosperatosisField;
    
    private string f_logosperatosiscommentsField;
    
    private string f_afm_proswpoyField;
    
    private byte[] f_fileField;
    
    private byte[] f_foreign_fileField;
    
    private byte[] f_young_fileField;

    public void initialize()
    {
        this.f_rel_protocol = "";
        this.f_rel_date = "";
        this.f_ergodotikh_organwsh = "";
        this.f_kad_deyt_1 = "";
        this.f_kad_deyt_2 = "";
        this.f_kad_deyt_3 = "";
        this.f_kad_deyt_4 = "";

        this.f_eponymo_mitros = "";
        this.f_eponymo_patros = "";
        this.f_topos_gennhshs = "";
        this.f_ekdousa_arxh = "";
        this.f_date_ekdosis = "";
        this.f_date_ekdosis_lixi = "";
        this.f_res_permit_inst_type = "";
        this.f_res_permit_inst_ar = "";
        this.f_res_permit_inst_lixi = "";
        this.f_res_permit_ap_type = "";
        this.f_res_permit_ap_ar = "";
        this.f_res_permit_ap_lixi = "";
        this.f_res_permit_visa_ar = "";
        this.f_res_permit_visa_from = "";
        this.f_res_permit_visa_to = "";
        this.f_doy = "";
        this.f_amika = "";
        this.f_code_anergias = "";
        this.f_ar_vivliou_anilikou = "";
        this.f_dieythinsi = "";
        this.f_kallikratis = "";
        this.f_tk = "";
        this.f_til = "";
        this.f_fl1 = "";
        this.f_fl2 = "";
        this.f_fl3 = "";
        this.f_fl4 = "";
        this.f_fax = "";
        this.f_expertise_field = "";
        this.f_pc_other = "";
        this.f_email = "";
        this.f_subject_area = "";
        this.f_subject_group = "";
        this.f_education_agency = "";
        this.f_education_date_from = "";
        this.f_education_date_to = "";
        this.f_education_year = "";
        this.f_duration = "";
        this.f_comments = "";
        this.f_logosperatosiscomments = "";
        this.f_file = new byte[] { };
        this.f_foreign_file = new byte[] { };
        this.f_young_file = new byte[] { };
    }
    public void copyFromContract(Contract contract)
    {
        this.f_afm = contract.afm;
        this.f_eponymo = contract.eponymo;
        this.f_onoma = contract.onoma;
        this.f_onoma_patros = contract.onoma_patros;
        this.f_onoma_mitros = contract.onoma_mitros;
        this.f_birthdate = contract.birthdate;
        this.f_sex = contract.sex;
        this.f_ar_taytothtas = contract.adt;
        this.f_typos_taytothtas = "ΔAT";
        this.f_marital_status = contract.maritalStatus;
        this.f_arithmos_teknon = contract.arithmos_teknon;
        this.f_amka = contract.amka;
        this.f_xaraktirismos = AnaggeliaE7TypeF_xaraktirismos.ypallhlos;
        this.f_sxeshapasxolisis = AnaggeliaE7TypeF_sxeshapasxolisis.orismenoyXronoy;
        this.f_eidikothta = contract.kodikosEidikotitas;
        this.f_apodoxes = contract.misthos.ToString("0.00");
        this.f_proslipsidate = contract.proslipsidate;
        this.f_epipedo_morfosis = contract.epipedo_morfosis;

        this.f_apolysisdate = contract.apolysisdate.ToString("dd/MM/yyyy"); 
        this.f_lixisymbashdate = contract.symvatikhHmeromhniaLh3hsSymvashs.ToString("dd/MM/yyyy");
        //this.f_lastdaydate = contract.lastWorkedOnDate.ToString("dd/MM/yyyy");
        this.f_logosperatosis = AnaggeliaE7TypeF_logosperatosis.Item0;

        this.f_kathestosapasxolisis = contract.kathestosApasxolisis;
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_aa_pararthmatos {
        get {
            return this.f_aa_pararthmatosField;
        }
        set {
            this.f_aa_pararthmatosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_rel_protocol {
        get {
            return this.f_rel_protocolField;
        }
        set {
            this.f_rel_protocolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_rel_date {
        get {
            return this.f_rel_dateField;
        }
        set {
            this.f_rel_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_ypiresia_sepe {
        get {
            return this.f_ypiresia_sepeField;
        }
        set {
            this.f_ypiresia_sepeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_ypiresia_oaed {
        get {
            return this.f_ypiresia_oaedField;
        }
        set {
            this.f_ypiresia_oaedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_ergodotikh_organwsh {
        get {
            return this.f_ergodotikh_organwshField;
        }
        set {
            this.f_ergodotikh_organwshField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_kad_kyria {
        get {
            return this.f_kad_kyriaField;
        }
        set {
            this.f_kad_kyriaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_kad_deyt_1 {
        get {
            return this.f_kad_deyt_1Field;
        }
        set {
            this.f_kad_deyt_1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_kad_deyt_2 {
        get {
            return this.f_kad_deyt_2Field;
        }
        set {
            this.f_kad_deyt_2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_kad_deyt_3 {
        get {
            return this.f_kad_deyt_3Field;
        }
        set {
            this.f_kad_deyt_3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_kad_deyt_4 {
        get {
            return this.f_kad_deyt_4Field;
        }
        set {
            this.f_kad_deyt_4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_kad_pararthmatos {
        get {
            return this.f_kad_pararthmatosField;
        }
        set {
            this.f_kad_pararthmatosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_kallikratis_pararthmatos {
        get {
            return this.f_kallikratis_pararthmatosField;
        }
        set {
            this.f_kallikratis_pararthmatosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_eponymo {
        get {
            return this.f_eponymoField;
        }
        set {
            this.f_eponymoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_onoma {
        get {
            return this.f_onomaField;
        }
        set {
            this.f_onomaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_eponymo_patros {
        get {
            return this.f_eponymo_patrosField;
        }
        set {
            this.f_eponymo_patrosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_onoma_patros {
        get {
            return this.f_onoma_patrosField;
        }
        set {
            this.f_onoma_patrosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_eponymo_mitros {
        get {
            return this.f_eponymo_mitrosField;
        }
        set {
            this.f_eponymo_mitrosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_onoma_mitros {
        get {
            return this.f_onoma_mitrosField;
        }
        set {
            this.f_onoma_mitrosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_topos_gennhshs {
        get {
            return this.f_topos_gennhshsField;
        }
        set {
            this.f_topos_gennhshsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_birthdate {
        get {
            return this.f_birthdateField;
        }
        set {
            this.f_birthdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7TypeF_sex f_sex {
        get {
            return this.f_sexField;
        }
        set {
            this.f_sexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_yphkoothta {
        get {
            return this.f_yphkoothtaField;
        }
        set {
            this.f_yphkoothtaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_typos_taytothtas {
        get {
            return this.f_typos_taytothtasField;
        }
        set {
            this.f_typos_taytothtasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_ar_taytothtas {
        get {
            return this.f_ar_taytothtasField;
        }
        set {
            this.f_ar_taytothtasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_ekdousa_arxh {
        get {
            return this.f_ekdousa_arxhField;
        }
        set {
            this.f_ekdousa_arxhField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_date_ekdosis {
        get {
            return this.f_date_ekdosisField;
        }
        set {
            this.f_date_ekdosisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_date_ekdosis_lixi {
        get {
            return this.f_date_ekdosis_lixiField;
        }
        set {
            this.f_date_ekdosis_lixiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7TypeF_res_permit_inst f_res_permit_inst {
        get {
            return this.f_res_permit_instField;
        }
        set {
            this.f_res_permit_instField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_res_permit_inst_type {
        get {
            return this.f_res_permit_inst_typeField;
        }
        set {
            this.f_res_permit_inst_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_res_permit_inst_ar {
        get {
            return this.f_res_permit_inst_arField;
        }
        set {
            this.f_res_permit_inst_arField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_res_permit_inst_lixi {
        get {
            return this.f_res_permit_inst_lixiField;
        }
        set {
            this.f_res_permit_inst_lixiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7TypeF_res_permit_ap f_res_permit_ap {
        get {
            return this.f_res_permit_apField;
        }
        set {
            this.f_res_permit_apField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_res_permit_ap_type {
        get {
            return this.f_res_permit_ap_typeField;
        }
        set {
            this.f_res_permit_ap_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_res_permit_ap_ar {
        get {
            return this.f_res_permit_ap_arField;
        }
        set {
            this.f_res_permit_ap_arField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_res_permit_ap_lixi {
        get {
            return this.f_res_permit_ap_lixiField;
        }
        set {
            this.f_res_permit_ap_lixiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7TypeF_res_permit_visa f_res_permit_visa {
        get {
            return this.f_res_permit_visaField;
        }
        set {
            this.f_res_permit_visaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_res_permit_visa_ar {
        get {
            return this.f_res_permit_visa_arField;
        }
        set {
            this.f_res_permit_visa_arField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_res_permit_visa_from {
        get {
            return this.f_res_permit_visa_fromField;
        }
        set {
            this.f_res_permit_visa_fromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_res_permit_visa_to {
        get {
            return this.f_res_permit_visa_toField;
        }
        set {
            this.f_res_permit_visa_toField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7TypeF_marital_status f_marital_status {
        get {
            return this.f_marital_statusField;
        }
        set {
            this.f_marital_statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_arithmos_teknon {
        get {
            return this.f_arithmos_teknonField;
        }
        set {
            this.f_arithmos_teknonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_afm {
        get {
            return this.f_afmField;
        }
        set {
            this.f_afmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_doy {
        get {
            return this.f_doyField;
        }
        set {
            this.f_doyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_amika {
        get {
            return this.f_amikaField;
        }
        set {
            this.f_amikaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_amka {
        get {
            return this.f_amkaField;
        }
        set {
            this.f_amkaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_code_anergias {
        get {
            return this.f_code_anergiasField;
        }
        set {
            this.f_code_anergiasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_ar_vivliou_anilikou {
        get {
            return this.f_ar_vivliou_anilikouField;
        }
        set {
            this.f_ar_vivliou_anilikouField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_dieythinsi {
        get {
            return this.f_dieythinsiField;
        }
        set {
            this.f_dieythinsiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_kallikratis {
        get {
            return this.f_kallikratisField;
        }
        set {
            this.f_kallikratisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_tk {
        get {
            return this.f_tkField;
        }
        set {
            this.f_tkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_til {
        get {
            return this.f_tilField;
        }
        set {
            this.f_tilField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_fax {
        get {
            return this.f_faxField;
        }
        set {
            this.f_faxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_email {
        get {
            return this.f_emailField;
        }
        set {
            this.f_emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_epipedo_morfosis {
        get {
            return this.f_epipedo_morfosisField;
        }
        set {
            this.f_epipedo_morfosisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7TypeF_professional_education f_professional_education {
        get {
            return this.f_professional_educationField;
        }
        set {
            this.f_professional_educationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_expertise_field {
        get {
            return this.f_expertise_fieldField;
        }
        set {
            this.f_expertise_fieldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_subject_area {
        get {
            return this.f_subject_areaField;
        }
        set {
            this.f_subject_areaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_subject_group {
        get {
            return this.f_subject_groupField;
        }
        set {
            this.f_subject_groupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_education_agency {
        get {
            return this.f_education_agencyField;
        }
        set {
            this.f_education_agencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_education_date_from {
        get {
            return this.f_education_date_fromField;
        }
        set {
            this.f_education_date_fromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_education_date_to {
        get {
            return this.f_education_date_toField;
        }
        set {
            this.f_education_date_toField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_duration {
        get {
            return this.f_durationField;
        }
        set {
            this.f_durationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_education_year {
        get {
            return this.f_education_yearField;
        }
        set {
            this.f_education_yearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_fl1 {
        get {
            return this.f_fl1Field;
        }
        set {
            this.f_fl1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_fl2 {
        get {
            return this.f_fl2Field;
        }
        set {
            this.f_fl2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_fl3 {
        get {
            return this.f_fl3Field;
        }
        set {
            this.f_fl3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_fl4 {
        get {
            return this.f_fl4Field;
        }
        set {
            this.f_fl4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7TypeF_pc f_pc {
        get {
            return this.f_pcField;
        }
        set {
            this.f_pcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_pc_other {
        get {
            return this.f_pc_otherField;
        }
        set {
            this.f_pc_otherField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7TypeF_xaraktirismos f_xaraktirismos {
        get {
            return this.f_xaraktirismosField;
        }
        set {
            this.f_xaraktirismosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7TypeF_sxeshapasxolisis f_sxeshapasxolisis {
        get {
            return this.f_sxeshapasxolisisField;
        }
        set {
            this.f_sxeshapasxolisisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7TypeF_kathestosapasxolisis f_kathestosapasxolisis {
        get {
            return this.f_kathestosapasxolisisField;
        }
        set {
            this.f_kathestosapasxolisisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7TypeF_oros f_oros {
        get {
            return this.f_orosField;
        }
        set {
            this.f_orosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_eidikothta {
        get {
            return this.f_eidikothtaField;
        }
        set {
            this.f_eidikothtaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_apodoxes {
        get {
            return this.f_apodoxesField;
        }
        set {
            this.f_apodoxesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_proslipsidate {
        get {
            return this.f_proslipsidateField;
        }
        set {
            this.f_proslipsidateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_lixisymbashdate {
        get {
            return this.f_lixisymbashdateField;
        }
        set {
            this.f_lixisymbashdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_apolysisdate {
        get {
            return this.f_apolysisdateField;
        }
        set {
            this.f_apolysisdateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_comments
    {
        get
        {
            return this.f_commentsField;
        }
        set
        {
            this.f_commentsField = value;
        }
    }


    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7TypeF_logosperatosis f_logosperatosis {
        get {
            return this.f_logosperatosisField;
        }
        set {
            this.f_logosperatosisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_logosperatosiscomments {
        get {
            return this.f_logosperatosiscommentsField;
        }
        set {
            this.f_logosperatosiscommentsField = value;
        }
    }



    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_afm_proswpoy {
        get {
            return this.f_afm_proswpoyField;
        }
        set {
            this.f_afm_proswpoyField = value;
        }
    }


    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
    public byte[] f_file {
        get {
            return this.f_fileField;
        }
        set {
            this.f_fileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
    public byte[] f_foreign_file {
        get {
            return this.f_foreign_fileField;
        }
        set {
            this.f_foreign_fileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
    public byte[] f_young_file {
        get {
            return this.f_young_fileField;
        }
        set {
            this.f_young_fileField = value;
        }
    }


    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_lastdaydate
    {
        get
        {
            return this.f_lastdaydateField;
        }
        set
        {
            this.f_lastdaydateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yeka.gr/E7")]
public enum AnaggeliaE7TypeF_sex {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    male,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    female,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yeka.gr/E7")]
public enum AnaggeliaE7TypeF_res_permit_inst {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("")]
    Item,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yeka.gr/E7")]
public enum AnaggeliaE7TypeF_res_permit_ap {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("")]
    Item,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yeka.gr/E7")]
public enum AnaggeliaE7TypeF_res_permit_visa {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("")]
    Item,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yeka.gr/E7")]
public enum AnaggeliaE7TypeF_marital_status {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    notMarried,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    married,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    divorced,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    widowed,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yeka.gr/E7")]
public enum AnaggeliaE7TypeF_professional_education {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("")]
    Item,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yeka.gr/E7")]
public enum AnaggeliaE7TypeF_pc {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("")]
    Item,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yeka.gr/E7")]
public enum AnaggeliaE7TypeF_xaraktirismos {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    ergaths,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    ypallhlos,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yeka.gr/E7")]
public enum AnaggeliaE7TypeF_sxeshapasxolisis {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    orismenoyXronoy,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    symvashErgoy,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yeka.gr/E7")]
public enum AnaggeliaE7TypeF_kathestosapasxolisis {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    plhrhs,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    merikh,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    ekperitrophs,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yeka.gr/E7")]
public enum AnaggeliaE7TypeF_oros {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yeka.gr/E7")]
public enum AnaggeliaE7TypeF_logosperatosis {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Item2,
}
