//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yeka.gr/E7N")]
[System.Xml.Serialization.XmlRootAttribute("AnaggeliesE7N", Namespace="http://www.yeka.gr/E7N", IsNullable=false)]
public partial class AnaggeliesE7NType {
    
    private AnaggeliaE7NType[] anaggeliaE7NField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AnaggeliaE7N", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7NType[] AnaggeliaE7N {
        get {
            return this.anaggeliaE7NField;
        }
        set {
            this.anaggeliaE7NField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.yeka.gr/E7N")]
public partial class AnaggeliaE7NType {
    
    private string f_aa_pararthmatosField;
    
    private string f_rel_protocolField;
    
    private string f_rel_dateField;
    
    private string f_ypiresia_sepeField;
    
    private string f_ypiresia_oaedField;
    
    private string f_kad_pararthmatosField;
    
    private string f_kallikratis_pararthmatosField;
    
    private string f_eponymoField;
    
    private string f_onomaField;
    
    private string f_onoma_patrosField;
    
    private string f_onoma_mitrosField;
    
    private string f_birthdateField;
    
    private AnaggeliaE7NTypeF_sex f_sexField;
    
    private string f_yphkoothtaField;
    
    private string f_typos_taytothtasField;
    
    private string f_ar_taytothtasField;
    
    private string f_ekdousa_arxhField;
    
    private string f_date_ekdosisField;
    
    private string f_date_ekdosis_lixiField;
    
    private AnaggeliaE7NTypeF_res_permit_inst f_res_permit_instField;
    
    private string f_res_permit_inst_typeField;
    
    private string f_res_permit_inst_arField;
    
    private string f_res_permit_inst_lixiField;
    
    private AnaggeliaE7NTypeF_res_permit_ap f_res_permit_apField;
    
    private string f_res_permit_ap_typeField;
    
    private string f_res_permit_ap_arField;
    
    private string f_res_permit_ap_lixiField;
    
    private AnaggeliaE7NTypeF_res_permit_visa f_res_permit_visaField;
    
    private string f_res_permit_visa_arField;
    
    private string f_res_permit_visa_fromField;
    
    private string f_res_permit_visa_toField;
    
    private AnaggeliaE7NTypeF_marital_status f_marital_statusField;
    
    private string f_arithmos_teknonField;
    
    private string f_afmField;
    
    private string f_doyField;
    
    private string f_amikaField;
    
    private string f_amkaField;
    
    private string f_code_anergiasField;
    
    private string f_ar_vivliou_anilikouField;
    
    private string f_epipedo_morfosisField;
    
    private AnaggeliaE7NTypeF_xaraktirismos f_xaraktirismosField;
    
    private AnaggeliaE7NTypeF_sxeshapasxolisis f_sxeshapasxolisisField;
    
    private AnaggeliaE7NTypeF_kathestosapasxolisis f_kathestosapasxolisisField;
    
    private AnaggeliaE7NTypeF_oros f_orosField;
    
    private string f_eidikothtaField;
    
    private string f_apodoxesField;
    
    private string f_proslipsidateField;
    
    private string f_lixisymbashdateField;
    
    private string f_apolysisdateField;
    
    private string f_commentsField;
    
    private AnaggeliaE7NTypeF_logosperatosis f_logosperatosisField;
    
    private string f_logosperatosiscommentsField;
    
    private byte[] f_foreign_fileField;
    
    private byte[] f_young_fileField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_aa_pararthmatos {
        get {
            return this.f_aa_pararthmatosField;
        }
        set {
            this.f_aa_pararthmatosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_rel_protocol {
        get {
            return this.f_rel_protocolField;
        }
        set {
            this.f_rel_protocolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_rel_date {
        get {
            return this.f_rel_dateField;
        }
        set {
            this.f_rel_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_ypiresia_sepe {
        get {
            return this.f_ypiresia_sepeField;
        }
        set {
            this.f_ypiresia_sepeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_ypiresia_oaed {
        get {
            return this.f_ypiresia_oaedField;
        }
        set {
            this.f_ypiresia_oaedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_kad_pararthmatos {
        get {
            return this.f_kad_pararthmatosField;
        }
        set {
            this.f_kad_pararthmatosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_kallikratis_pararthmatos {
        get {
            return this.f_kallikratis_pararthmatosField;
        }
        set {
            this.f_kallikratis_pararthmatosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_eponymo {
        get {
            return this.f_eponymoField;
        }
        set {
            this.f_eponymoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_onoma {
        get {
            return this.f_onomaField;
        }
        set {
            this.f_onomaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_onoma_patros {
        get {
            return this.f_onoma_patrosField;
        }
        set {
            this.f_onoma_patrosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_onoma_mitros {
        get {
            return this.f_onoma_mitrosField;
        }
        set {
            this.f_onoma_mitrosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_birthdate {
        get {
            return this.f_birthdateField;
        }
        set {
            this.f_birthdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7NTypeF_sex f_sex {
        get {
            return this.f_sexField;
        }
        set {
            this.f_sexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_yphkoothta {
        get {
            return this.f_yphkoothtaField;
        }
        set {
            this.f_yphkoothtaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_typos_taytothtas {
        get {
            return this.f_typos_taytothtasField;
        }
        set {
            this.f_typos_taytothtasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_ar_taytothtas {
        get {
            return this.f_ar_taytothtasField;
        }
        set {
            this.f_ar_taytothtasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_ekdousa_arxh {
        get {
            return this.f_ekdousa_arxhField;
        }
        set {
            this.f_ekdousa_arxhField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_date_ekdosis {
        get {
            return this.f_date_ekdosisField;
        }
        set {
            this.f_date_ekdosisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_date_ekdosis_lixi {
        get {
            return this.f_date_ekdosis_lixiField;
        }
        set {
            this.f_date_ekdosis_lixiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7NTypeF_res_permit_inst f_res_permit_inst {
        get {
            return this.f_res_permit_instField;
        }
        set {
            this.f_res_permit_instField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_res_permit_inst_type {
        get {
            return this.f_res_permit_inst_typeField;
        }
        set {
            this.f_res_permit_inst_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_res_permit_inst_ar {
        get {
            return this.f_res_permit_inst_arField;
        }
        set {
            this.f_res_permit_inst_arField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_res_permit_inst_lixi {
        get {
            return this.f_res_permit_inst_lixiField;
        }
        set {
            this.f_res_permit_inst_lixiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7NTypeF_res_permit_ap f_res_permit_ap {
        get {
            return this.f_res_permit_apField;
        }
        set {
            this.f_res_permit_apField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_res_permit_ap_type {
        get {
            return this.f_res_permit_ap_typeField;
        }
        set {
            this.f_res_permit_ap_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_res_permit_ap_ar {
        get {
            return this.f_res_permit_ap_arField;
        }
        set {
            this.f_res_permit_ap_arField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_res_permit_ap_lixi {
        get {
            return this.f_res_permit_ap_lixiField;
        }
        set {
            this.f_res_permit_ap_lixiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7NTypeF_res_permit_visa f_res_permit_visa {
        get {
            return this.f_res_permit_visaField;
        }
        set {
            this.f_res_permit_visaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_res_permit_visa_ar {
        get {
            return this.f_res_permit_visa_arField;
        }
        set {
            this.f_res_permit_visa_arField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_res_permit_visa_from {
        get {
            return this.f_res_permit_visa_fromField;
        }
        set {
            this.f_res_permit_visa_fromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_res_permit_visa_to {
        get {
            return this.f_res_permit_visa_toField;
        }
        set {
            this.f_res_permit_visa_toField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7NTypeF_marital_status f_marital_status {
        get {
            return this.f_marital_statusField;
        }
        set {
            this.f_marital_statusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_arithmos_teknon {
        get {
            return this.f_arithmos_teknonField;
        }
        set {
            this.f_arithmos_teknonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_afm {
        get {
            return this.f_afmField;
        }
        set {
            this.f_afmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_doy {
        get {
            return this.f_doyField;
        }
        set {
            this.f_doyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_amika {
        get {
            return this.f_amikaField;
        }
        set {
            this.f_amikaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_amka {
        get {
            return this.f_amkaField;
        }
        set {
            this.f_amkaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_code_anergias {
        get {
            return this.f_code_anergiasField;
        }
        set {
            this.f_code_anergiasField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_ar_vivliou_anilikou {
        get {
            return this.f_ar_vivliou_anilikouField;
        }
        set {
            this.f_ar_vivliou_anilikouField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_epipedo_morfosis {
        get {
            return this.f_epipedo_morfosisField;
        }
        set {
            this.f_epipedo_morfosisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7NTypeF_xaraktirismos f_xaraktirismos {
        get {
            return this.f_xaraktirismosField;
        }
        set {
            this.f_xaraktirismosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7NTypeF_sxeshapasxolisis f_sxeshapasxolisis {
        get {
            return this.f_sxeshapasxolisisField;
        }
        set {
            this.f_sxeshapasxolisisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7NTypeF_kathestosapasxolisis f_kathestosapasxolisis {
        get {
            return this.f_kathestosapasxolisisField;
        }
        set {
            this.f_kathestosapasxolisisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7NTypeF_oros f_oros {
        get {
            return this.f_orosField;
        }
        set {
            this.f_orosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_eidikothta {
        get {
            return this.f_eidikothtaField;
        }
        set {
            this.f_eidikothtaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_apodoxes {
        get {
            return this.f_apodoxesField;
        }
        set {
            this.f_apodoxesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_proslipsidate {
        get {
            return this.f_proslipsidateField;
        }
        set {
            this.f_proslipsidateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_lixisymbashdate {
        get {
            return this.f_lixisymbashdateField;
        }
        set {
            this.f_lixisymbashdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_apolysisdate {
        get {
            return this.f_apolysisdateField;
        }
        set {
            this.f_apolysisdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_comments {
        get {
            return this.f_commentsField;
        }
        set {
            this.f_commentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public AnaggeliaE7NTypeF_logosperatosis f_logosperatosis {
        get {
            return this.f_logosperatosisField;
        }
        set {
            this.f_logosperatosisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string f_logosperatosiscomments {
        get {
            return this.f_logosperatosiscommentsField;
        }
        set {
            this.f_logosperatosiscommentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
    public byte[] f_foreign_file {
        get {
            return this.f_foreign_fileField;
        }
        set {
            this.f_foreign_fileField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
    public byte[] f_young_file {
        get {
            return this.f_young_fileField;
        }
        set {
            this.f_young_fileField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yeka.gr/E7N")]
public enum AnaggeliaE7NTypeF_sex {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    male,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    female,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yeka.gr/E7N")]
public enum AnaggeliaE7NTypeF_res_permit_inst {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("")]
    Item,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yeka.gr/E7N")]
public enum AnaggeliaE7NTypeF_res_permit_ap {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("")]
    Item,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yeka.gr/E7N")]
public enum AnaggeliaE7NTypeF_res_permit_visa {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("")]
    Item,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Item0,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yeka.gr/E7N")]
public enum AnaggeliaE7NTypeF_marital_status {

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    notMarried,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    married,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    divorced,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    widowed,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yeka.gr/E7N")]
public enum AnaggeliaE7NTypeF_xaraktirismos {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    Ergaths,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    ypallhlos,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yeka.gr/E7N")]
public enum AnaggeliaE7NTypeF_sxeshapasxolisis {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    OrismenouXronou,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    Ergou,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yeka.gr/E7N")]
public enum AnaggeliaE7NTypeF_kathestosapasxolisis {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    plhrhs,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    merikh,

    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2")]
    ekperitrophs,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yeka.gr/E7N")]
public enum AnaggeliaE7NTypeF_oros {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    OXI,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    NAI,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.yeka.gr/E7N")]
public enum AnaggeliaE7NTypeF_logosperatosis {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("0")]
    LhxhSympefwnhmenouXronou,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("3")]
    Item3,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("4")]
    Item4,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("5")]
    Item5,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("6")]
    Item6,
}
